# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python



name: Python CI

#Trigger the workflow on any push to the main branch or pull request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            #Step 1: Check out the code from the repository
            
            - name: Check out code
              uses: actions/checkout@v4

            #Step 2: Setup Python
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: '3.10'
            
            #Step 3: Install Dependencies

            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            
            # Step 4: Run tests
            - name: Run tests
              run: python -m unittest discover tests
